version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: git checkout  feature/circleci_initial_setting
      - run: echo "hello world"